### ISSUE TITLE
Uncaught TypeError: Cannot read property 'decoder' of null

### ISSUE THREAD

**Issue by gdotdesign** [elm-lang/virtual-dom#7] opened 2016-05-05 05:37 UTC
Got the above error for this code: https://gist.github.com/gdotdesign/4d4985415b1d4daca4fb48aee01bbd50

Changing the oder of the style attribute changes the behavior, if it's at the top it's the #4 issue, if it's the middle or the bottom then the error above.

**Comment by evancz** [comment] 2016-05-05 05:51
Seems to be resolved with the fix for #6. Can you confirm?

**Closed by evancz** 2016-05-05 05:51 UTC

**Comment by gdotdesign** [comment] 2016-05-05 06:02
Yes, it works, thanks!

**Comment by michaeljones** [comment] 2016-05-18 20:10
Hi,

I'm seeing this error as well with 0.17. This gist reproduces it for me, I hope it does for you as well.

https://gist.github.com/michaeljones/f2ba0275645f7e522f78f749a0a1dce8

I appear to have the fix you previously applied so I think this is another issue. Happy to create another issue if you'd prefer. In my case, as noted in the comment in the gist, it seems to be associated with having an `onClick` attribute and then removing it. I hope it is clear from the gist.

Loving Elm otherwise :)
Michael

**Comment by gdotdesign** [comment] 2016-05-19 03:45
I think it's the same as #12 basically event listeners are not getting removed.

**Comment by michaeljones** [comment] 2016-05-19 09:46
Ah, thanks. I was fixated on the error message so didn't shop around for other issues. Looks like the same thing.
