### ISSUE TITLE
Debugger crash runtime when model consists of a big List String

### ISSUE THREAD

**Issue by johannesl** [elm-lang/virtual-dom#86] opened 2017-02-06 16:37 UTC
What was first experienced as a problem with decoding a list of many string items with Json.Decode turned out to be isolated to elm-reactor running in debug mode. The problem is triggered when the model contains a List String with about 15000 elements.

@unsoundscapes in the Elm Slack suggested this was related to the debugger wanting to traverse the model in order to display it.

You can find code that reproduces this error here:
https://github.com/johannesl/elm-issue1521

Google Chrome on macOS (55.0.2883.95) is effected, and throws a "Maximum call stack size exceeded" error. The problem triggers in neither Safari nor Firefox on macOS.

**Comment by ianmackenzie** [comment] 2017-03-29 21:21
I suspect this is a duplicate of #80.

**Comment by evancz** [comment] 2017-05-19 01:36
Tracking in #98. Thanks for the report!

**Closed by evancz** 2017-05-19 01:36 UTC
